using Azure.AI.OpenAI;
using Azure.Identity;
using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;
using OpenAI.Chat;
using ChatMessage = Microsoft.Extensions.AI.ChatMessage;


Console.WriteLine("--- Initializing Remote Mentorship Swarm ---");

// 1. Define the Hosted MCP Tool with Governance
// We connect to the remote SSE endpoint and explicitly demand human approval before execution.
var mcpHostedTool = new HostedMcpServerTool(
    serverName: "microsoft_learn",
    serverAddress: "https://learn.microsoft.com/api/mcp")
{
    // Restrict the agent to only use the search tool
    AllowedTools = ["microsoft_docs_search"],
    // GOVERNANCE: Force the agent to pause and ask permission before crossing the network boundary
    ApprovalMode = HostedMcpServerToolApprovalMode.AlwaysRequire
};

// 2. Initialize the Agent
var endpoint = Environment.GetEnvironmentVariable("AZURE_OPENAI_ENDPOINT") ?? throw new InvalidOperationException("AZURE_OPENAI_ENDPOINT is not set.");
var deploymentName = Environment.GetEnvironmentVariable("AZURE_OPENAI_DEPLOYMENT_NAME") ?? "gpt-5-mini";

AIAgent mentorAgent = new AzureOpenAIClient(new Uri(endpoint), new AzureCliCredential())
    .GetChatClient(deploymentName)
    .AsAIAgent(
        name: "ArchitectureMentor",
        instructions: "You answer technical .NET questions. You MUST use the 'microsoft_docs_search' tool from the 'microsoft_learn' server before answering.",
        //instructions: "You are a Senior Architecture Mentor. To provide accurate answers, always start by calling the 'microsoft_docs_search' tool.",
        tools: [mcpHostedTool]
    );

Console.WriteLine($"Tools available: {string.Join(", ", mcpHostedTool.AllowedTools)}");

// 3. Begin the Stateful Session
AgentSession session = await mentorAgent.CreateSessionAsync();
//string prompt = "What are the exact C# classes required to implement the Agent-to-Agent (A2A) protocol in the Microsoft Agent Framework?";
string prompt = "What are the exact C# classes required to implement the Agent-to-Agent (A2A) protocol using the Microsoft.Agents.AI namespace?";

Console.WriteLine($"\nJunior Dev: {prompt}\n");

// 4. Initial Execution (The agent realizes it needs to search and pauses)
AgentResponse response = await mentorAgent.RunAsync(prompt, session);

// Extract any pending approval requests generated by the agent
List<ToolApprovalRequestContent> approvalRequests = response.Messages
    .SelectMany(m => m.Contents)
    .OfType<ToolApprovalRequestContent>()
    .ToList();

// 5. The Governance Loop (Human-in-the-Loop)
while (approvalRequests.Count > 0)
{
    // Process one request at a time, then refresh pending approvals from latest response.
    var request = approvalRequests[0];

    // Present the agent's intent to the human manager
    Console.WriteLine("\n[SECURITY AUDIT] The agent is attempting to execute a remote tool.");
    if (request.ToolCall is McpServerToolCallContent mcpToolCall)
    {
        Console.WriteLine($"Target Server: {mcpToolCall.ServerName}");
        Console.WriteLine($"Target Tool:   {mcpToolCall.Name}");

        string toolArgs = string.Join(", ", mcpToolCall.Arguments?.Select(x => $"{x.Key}: '{x.Value}'") ?? []);
        Console.WriteLine($"Arguments:     {toolArgs}");
    }
    else
    {
        Console.WriteLine("Target Tool:   [Unknown MCP tool call payload]");
    }

    Console.Write("\nApprove network request? (Y/N): ");
    ConsoleKey key;
    do
    {
        key = Console.ReadKey(intercept: true).Key;
    } while (key is not ConsoleKey.Y and not ConsoleKey.N);
    Console.WriteLine(key == ConsoleKey.Y ? "Y" : "N");

    bool isApproved = key == ConsoleKey.Y;

    // Package the human's decision back into a ChatMessage
    var approvalMessage = new ChatMessage(ChatRole.User, [request.CreateResponse(isApproved)]);

    // Push the human's approval (or denial) back to the agent and resume execution
    Console.WriteLine("\n[System] Resuming agent execution...");
    response = await mentorAgent.RunAsync(approvalMessage, session);

    // Check if the agent wants to execute *another* tool based on the new results
    approvalRequests = response.Messages
        .SelectMany(m => m.Contents)
        .OfType<ToolApprovalRequestContent>()
        .ToList();
}

// 6. Final Synthesis
Console.WriteLine($"\nSenior Mentor:\n{response.Text}");